comment: false

ignore:
  - "R/khroma-deprecated.R"
  - "R/khroma-defunct.R"
  - "R/zzz.R"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
